version: '3.8'
services: 
    api-service:
        build: .
        volumes:
          - type: bind
            source: ./src
            target: /src
        ports: 
            - 3001:3001
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1