version: '3.8'
services: 
    api-service:
        build: .
        volumes:
          - type: bind
            source: ./src
            target: /src
        environment: 
            FLASK_DEBUG: 1
            MONGO_URI: mongodb+srv://luiz:PmaYWAikRQUGs93T@apptenis.fgica.mongodb.net/Gallery
            AWS_ACCESS_KEY: AKIA2U3H5ZR6USQP6CUW
            AWS_SECRET_KEY: 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